// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace StorageSearch {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class GeneratedDefs {
		public static class @Keys {
			/// <summary>
			/// Get's the translation key for '<em>Storage Search</em>'
			/// </summary>
			public const string @StorageSearch = "StorageSearch";
			/// <summary>
			/// Get's the translation key for '<em>Show parent category</em>'
			/// </summary>
			public const string @StorageSearch_IncludeParentCategory = "StorageSearch.IncludeParentCategory";
			/// <summary>
			/// Get's the translation key for '<em>Include an item's first parent category in the storage filter.</em>'
			/// </summary>
			public const string @StorageSearch_IncludeParentCategoryTip = "StorageSearch.IncludeParentCategoryTip";
			/// <summary>
			/// Get's the translation key for '<em>Refill cells less than</em>'
			/// </summary>
			public const string @HaulingHysteresis_RefillCellsLabel = "HaulingHysteresis.RefillCellsLabel";
			/// <summary>
			/// Get's the translation key for '<em>Search</em>'
			/// </summary>
			public const string @StorageSearch_SearchWatermark = "StorageSearch.SearchWatermark";
		}
	}
}
