// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace StorageSearch {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class GeneratedDefs {
		public static class @StorageSearchKeys {
			/// <summary>
			/// Get's the translation key for '<em>Storage Search</em>'
			/// </summary>
			public const string @StorageSearch = "StorageSearch";
			/// <summary>
			/// Get's the translation key for '<em>Enable outfits filter</em>'
			/// </summary>
			public const string @StorageSearch_ForOutfits = "StorageSearch.ForOutfits";
			/// <summary>
			/// Get's the translation key for '<em>Show the search box in outfit manager.</em>'
			/// </summary>
			public const string @StorageSearch_ForOutfitsTip = "StorageSearch.ForOutfitsTip";
			/// <summary>
			/// Get's the translation key for '<em>Enable crafting filter</em>'
			/// </summary>
			public const string @StorageSearch_ForCrafting = "StorageSearch.ForCrafting";
			/// <summary>
			/// Get's the translation key for '<em>Show the search box in crafting bill details.</em>'
			/// </summary>
			public const string @StorageSearch_ForCraftingTip = "StorageSearch.ForCraftingTip";
			/// <summary>
			/// Get's the translation key for '<em>Refill cells less than</em>'
			/// </summary>
			public const string @HaulingHysteresis_RefillCellsLabel = "HaulingHysteresis.RefillCellsLabel";
		}
		public static class @SearchFilterKeys {
			/// <summary>
			/// Get's the translation key for '<em>Filter search</em>'
			/// </summary>
			public const string @ImprovedFilter = "ImprovedFilter";
			/// <summary>
			/// Get's the translation key for '<em>Show parent category</em>'
			/// </summary>
			public const string @ImprovedFilter_IncludeParentCategory = "ImprovedFilter.IncludeParentCategory";
			/// <summary>
			/// Get's the translation key for '<em>Include an item's first parent categoryKey in the search filter.</em>'
			/// </summary>
			public const string @ImprovedFilter_IncludeParentCategoryTip = "ImprovedFilter.IncludeParentCategoryTip";
			/// <summary>
			/// Get's the translation key for '<em>Search</em>'
			/// </summary>
			public const string @ImprovedFilter_SearchWatermark = "ImprovedFilter.SearchWatermark";
		}
	}
}
