// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace ImprovedFilter {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class GeneratedDefs {
		public static class @SearchFilterKeys {
			/// <summary>
			/// Get's the translation key for '<em>Filter search</em>'
			/// </summary>
			public const string @ImprovedFilter = "ImprovedFilter";
			/// <summary>
			/// Get's the translation key for '<em>Show parent category</em>'
			/// </summary>
			public const string @ImprovedFilter_IncludeParentCategory = "ImprovedFilter.IncludeParentCategory";
			/// <summary>
			/// Get's the translation key for '<em>Include an item's first parent categoryKey in the search filter.</em>'
			/// </summary>
			public const string @ImprovedFilter_IncludeParentCategoryTip = "ImprovedFilter.IncludeParentCategoryTip";
			/// <summary>
			/// Get's the translation key for '<em>Search</em>'
			/// </summary>
			public const string @ImprovedFilter_SearchWatermark = "ImprovedFilter.SearchWatermark";
		}
	}
}
